# This is a CI workflow for the fv3atm project.
#
# This workflow builds the documentation only.
#
# Ed Hartnett 1/8/24

name: docs
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:

    - name: checkout-fv3atm
      uses: actions/checkout@v3
      with:
        path: ${{ github.workspace }}/fv3atm

    - name: build_docs
      run: |
        cd fv3atm
        mkdir build
        cd build
        cmake -DENABLE_DOCS=ON ..
        make -j2 VERBOSE=1

